add('v', '<leader>lat', ':<C-u>AmcliLatex<CR>')
add('v', '<leader>lal', ':<C-u>AmcliLatexLine<CR>')
add('v', '<leader>lab', ':<C-u>AmcliLatexBlock<CR>')
add('v', '<leader>ams', ':<C-u>AmcliSimp<CR>')
add('v', '<leader>ame', ':<C-u>AmcliEval<CR>')
add('n', '<leader>ame', 'v%:<C-u>AmcliEval<CR>')
